# Built the site with the following command for production:
# > bundle exec jekyll serve --incremental --config "_config.yml,_config_local.yml"

limit_posts: 3
strict_front_matter: true


# exclude robots.txt
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .github
  - "script"
  - ".travis.yml"
  - "vendor"
  - robots.txt

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - wai-website-plugin
